## In-Class Activity - Cyber Security Data Analysis 
This notebook will guide you through the process of analyzing a cyber security dataset. Follow the TODO tasks to complete the assignment.

# Step 1: Importing the required libraries

TODO: Import the necessary libraries for data analysis and visualization.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
pd.options.display.max_rows = 999
warnings.filterwarnings("ignore")

# Step 2: Loading the dataset

TODO: Load the given dataset.

In [3]:
link = "./Data/CySecData.csv"
df = pd.read_csv(link)

# Step 3: Display the first few rows of the dataset
TODO: Import the necessary libraries for data analysis and visualization.

In [4]:
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
3,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

# Step 4: Initial info on the dataset.

TODO: Provide a summary of the dataset.

In [5]:
df.info()
df.describe(include='all')  # Gives a summary including categorical columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25192 entries, 0 to 25191
Data columns (total 42 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   duration                     25192 non-null  int64
 1   protocol_type                25192 non-null  object
 2   service                      25192 non-null  object
 3   flag                         25192 non-null  object
 4   src_bytes                    25192 non-null  int64
 5   dst_bytes                    25192 non-null  int64
 6   land                         25192 non-null  int64
 7   wrong_fragment               25192 non-null  int64
 8   urgent                       25192 non-null  int64
 9   hot                          25192 non-null  int64
 10  num_failed_logins            25192 non-null  int64
 11  logged_in                    25192 non-null  int64
 12  num_compromised              25192 non-null  int64
 13  root_shell                   25192 non-null  int64
 14  su_attempted                 25192 non-null  int64
 15  num_root                     25192 non-null  int64
 16  num_file_creations           25192 non-null  int64
 17  num_shells                   25192 non-null  int64
 18  num_access_files             25192 non-null  int64
 19  num_outbound_cmds            25192 non-null  int64
 20  is_host_login                25192 non-null  int64
 21  is_guest_login               25192 non-null  int64
 22  count                        25192 non-null  int64
 23  srv_count                    25192 non-null  int64
 24  serror_rate                  25192 non-null  float64
 25  srv_serror_rate              25192 non-null  float64
 26  rerror_rate                  25192 non-null  float64
 27  srv_rerror_rate              25192 non-null  float64
 28  same_srv_rate                25192 non-null  float64
 29  diff_srv_rate                25192 non-null  float64
 30  srv_diff_host_rate           25192 non-null  float64
 31  dst_host_count               25192 non-null  int64
 32  dst_host_srv_count           25192 non-null  int64
 33  dst_host_same_srv_rate       25192 non-null  float64
 34  dst_host_diff_srv_rate       25192 non-null  float64
 35  dst_host_same_src_port_rate  25192 non-null  float64
 36  dst_host_srv_diff_host_rate  25192 non-null  float64
 37  dst_host_serror_rate         25192 non-null  float64
 38  dst_host_srv_serror_rate     25192 non-null  float64
 39  dst_host_rerror_rate         25192 non-null  float64
 40  dst_host_srv_rerror_rate     25192 non-null  float64
 41  class                        25192 non-null  object
dtypes: float64(15), int64(23), object(4)
memory usage: 8.1+ MB

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
count,25192.000000,25192,25192,25192,2.519200e+04,2.519200e+04,25192.000000,25192.000000,25192.00000,25192.000000,...,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192
unique,NaN,3,66,11,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,NaN,tcp,http,SF,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal
freq,NaN,20526,8003,14973,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13449
mean,305.054104,NaN,NaN,NaN,2.433063e+04,3.491847e+03,0.000079,0.023738,0.00004,0.198039,...,115.063036,0.519791,0.082539,0.147453,0.031844,0.285800,0.279846,0.117800,0.118769,NaN
std,2686.555640,NaN,NaN,NaN,2.410805e+06,8.883072e+04,0.008910,0.260221,0.00630,2.154202,...,110.646850,0.448944,0.187191,0.308367,0.110575,0.445316,0.446075,0.305869,0.317333,NaN
min,0.000000,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,0.000000,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000,0.00000,0.000000,...,10.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
50%,0.000000,NaN,NaN,NaN,4.400000e+01,0.000000e+00,0.000000,0.000000,0.00000,0.000000,...,61.000000,0.510000,0.030000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
75%,0.000000,NaN,NaN,NaN,2.790000e+02,5.302500e+02,0.000000,0.000000,0.00000,0.000000,...,255.000000,1.000000,0.070000,0.060000,0.020000,1.000000,1.000000,0.000000,0.000000,NaN
max,42862.000000,NaN,NaN,NaN,3.817091e+08,5.151385e+06,1.000000,3.000000,1.00000,77.000000,...,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN

# Step 5: Creating dummy variables
TODO: Create dummy variables for the categorical columns except for the label column "class".

In [6]:
dfDummies = pd.get_dummies(df.drop('class', axis=1), drop_first=True)

# Step 6: Dropping the target column
TODO: Drop the target column 'class' from the dataset.

In [7]:
dfDummies = dfDummies.drop

# Step 7: Importing the Standard Scaler
TODO: Import the `StandardScaler` from `sklearn.preprocessing`.

In [8]:
from sklearn.preprocessing import StandardScaler

# Step 8: Scaling the dataset
TODO: Scale the dataset using the `StandardScaler`.

In [17]:
print(type(dfDummies))

<class 'method'>

In [18]:
# Assuming df is your original DataFrame
dfDummies = pd.get_dummies(df, drop_first=True)

In [19]:
import numpy as np

# Step 1: Check column data types
print("Column data types:\n", dfDummies.dtypes)

# Step 2: Identify non-numeric columns
non_numeric_cols = dfDummies.select_dtypes(exclude=[np.number]).columns
print("Non-numeric columns:", list(non_numeric_cols))

# Step 3: Drop non-numeric columns
dfDummies_cleaned = dfDummies.drop(columns=non_numeric_cols)

# Step 4: Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
dfNormalized = pd.DataFrame(scaler.fit_transform(dfDummies_cleaned), columns=dfDummies_cleaned.columns)

Column data types:
 duration                         int64
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate                float64
rerror_rate                    float64
srv_rerror_rate                float64
same_srv_rate                  float64
diff_srv_rate                  float64
srv_diff_host_rate             float64
dst_host_count                   int64
dst_host_srv_count               int64
dst_host_same_srv_rate         float64
dst_host_diff_srv_rate         float64
dst_host_same_src_port_rate    float64
dst_host_srv_diff_host_rate    float64
dst_host_serror_rate           float64
dst_host_srv_serror_rate       float64
dst_host_rerror_rate           float64
dst_host_srv_rerror_rate       float64
protocol_type_tcp                 bool
protocol_type_udp                 bool
service_X11                       bool
service_Z39_50                    bool
service_auth                      bool
service_bgp                       bool
service_courier                   bool
service_csnet_ns                  bool
service_ctf                       bool
service_daytime                   bool
service_discard                   bool
service_domain                    bool
service_domain_u                  bool
service_echo                      bool
service_eco_i                     bool
service_ecr_i                     bool
service_efs                       bool
service_exec                      bool
service_finger                    bool
service_ftp                       bool
service_ftp_data                  bool
service_gopher                    bool
service_hostnames                 bool
service_http                      bool
service_http_443                  bool
service_http_8001                 bool
service_imap4                     bool
service_iso_tsap                  bool
service_klogin                    bool
service_kshell                    bool
service_ldap                      bool
service_link                      bool
service_login                     bool
service_mtp                       bool
service_name                      bool
service_netbios_dgm               bool
service_netbios_ns                bool
service_netbios_ssn               bool
service_netstat                   bool
service_nnsp                      bool
service_nntp                      bool
service_ntp_u                     bool
service_other                     bool
service_pm_dump                   bool
service_pop_2                     bool
service_pop_3                     bool
service_printer                   bool
service_private                   bool
service_red_i                     bool
service_remote_job                bool
service_rje                       bool
service_shell                     bool
service_smtp                      bool
service_sql_net                   bool
service_ssh                       bool
service_sunrpc                    bool
service_supdup                    bool
service_systat                    bool
service_telnet                    bool
service_tim_i                     bool
service_time                      bool
service_urh_i                     bool
service_urp_i                     bool
service_uucp                      bool
service_uucp_path                 bool
service_vmnet                     bool
service_whois                     bool
flag_REJ                          bool
flag_RSTO                         bool
flag_RSTOS0                       bool
flag_RSTR                         bool
flag_S0                           bool
flag_S1                           bool
flag_S2                           bool
flag_S3                           bool
flag_SF                           bool
flag_SH                           bool
class_normal                      bool
dtype: object
Non-numeric columns: ['protocol_type_tcp', 'protocol_type_udp', 'service_X11', 'service_Z39_50', 'service_auth', 'service_bgp', 'service_courier', 'service_csnet_ns', 'service_ctf', 'service_daytime', 'service_discard', 'service_domain', 'service_domain_u', 'service_echo', 'service_eco_i', 'service_ecr_i', 'service_efs', 'service_exec', 'service_finger', 'service_ftp', 'service_ftp_data', 'service_gopher', 'service_hostnames', 'service_http', 'service_http_443', 'service_http_8001', 'service_imap4', 'service_iso_tsap', 'service_klogin', 'service_kshell', 'service_ldap', 'service_link', 'service_login', 'service_mtp', 'service_name', 'service_netbios_dgm', 'service_netbios_ns', 'service_netbios_ssn', 'service_netstat', 'service_nnsp', 'service_nntp', 'service_ntp_u', 'service_other', 'service_pm_dump', 'service_pop_2', 'service_pop_3', 'service_printer', 'service_private', 'service_red_i', 'service_remote_job', 'service_rje', 'service_shell', 'service_smtp', 'service_sql_net', 'service_ssh', 'service_sunrpc', 'service_supdup', 'service_systat', 'service_telnet', 'service_tim_i', 'service_time', 'service_urh_i', 'service_urp_i', 'service_uucp', 'service_uucp_path', 'service_vmnet', 'service_whois', 'flag_REJ', 'flag_RSTO', 'flag_RSTOS0', 'flag_RSTR', 'flag_S0', 'flag_S1', 'flag_S2', 'flag_S3', 'flag_SF', 'flag_SH', 'class_normal']

In [20]:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
dfNormalized = pd.DataFrame(scaler.fit_transform(dfDummies), columns=dfDummies.columns)

# Step 9: Splitting the dataset
TODO: Split the dataset into features (X) and target (y).

In [21]:

y = df['class']
X = dfNormalized

# Step 10: Importing the required libraries for the models
TODO: Import the necessary libraries for model training and evaluation.

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, KFold
import numpy as np

# Step 11: Defining the models (Logistic Regression, Support Vector Machine, Random Forest)
TODO: Define the models to be evaluated.

In [23]:
models = []
models.append(('LR', LogisticRegression()))
models.append(('SVM', SVC()))
models.append(('RandomForestClassifier', RandomForestClassifier()))

# Step 12: Evaluating the models
TODO: Evaluate the models using 10 fold cross-validation and display the mean and standard deviation of the accuracy.
Hint: Use Kfold cross validation and a loop

In [24]:
# 10-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)

for name, model in models:
    cv_results = cross_val_score(model, X, y, cv=kfold, scoring='accuracy')
    print(f"{name}: Mean Accuracy = {cv_results.mean():.4f}, Std Dev = {cv_results.std():.4f}")

LR: Mean Accuracy = 1.0000, Std Dev = 0.0001
SVM: Mean Accuracy = 0.9982, Std Dev = 0.0007
RandomForestClassifier: Mean Accuracy = 1.0000, Std Dev = 0.0000

# Step 13: Converting the notebook to a script
TODO: Convert the notebook to a script using the `nbconvert` command.

In [27]:
!jupyter nbconvert --to script notebook.ipynb

[NbConvertApp] Converting notebook notebook.ipynb to script
[NbConvertApp] Writing 4031 bytes to notebook.py